name: 'Build and deploy the VDC toolkit'
description: 'Builds toolkit for VDC.'
author: 'Jack '
inputs:
outputs: 
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
  
branding:
  color: red
  icon: flag