name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v2

    - name: Log into Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS  }}  
       
       
    - name: Build the Docker image & Deploy
      shell : pwsh
      env:
        SERVICE_PRINCIPAL: ${{ secrets.SERVICE_PRINCIPAL }}
        SERVICE_PRINCIPAL_PASS: ${{ secrets.SERVICE_PRINCIPAL_PASS }}
        IS_DEV_OPS : "true"
        DEVOPS_SERVICE_PRINCIPAL_USER_ID: ${{ secrets.DEVOPS_SERVICE_PRINCIPAL_USER_ID }}
        ADMIN_USER_NAME: ${{ secrets.ADMIN_USER_NAME }}
        ADMIN_USER_PWD: ${{ secrets.ADMIN_USER_PWD }}
        DOMAIN_ADMIN_USERNAME: ${{ secrets.DOMAIN_ADMIN_USERNAME }}
        DOMAIN_ADMIN_USER_PWD: ${{ secrets.DOMAIN_ADMIN_USER_PWD }}
        ORGANIZATION_NAME : "MS"
        AZURE_LOCATION : "West US 2"
        AZURE_ENVIRONMENT_NAME : "AzureCloud"
        TENANT_ID : ${{ secrets.TENANT_ID }}
        SUBSCRIPTION_ID : ${{ secrets.SUBSCRIPTION_ID }}
        KEYVAULT_MANAGEMENT_USER_ID  : ${{ secrets.KEYVAULT_MANAGEMENT_USER_ID }}
        AZURE_DISCOVERY_URL : "https://management.azure.com/metadata/endpoints?api-version=2019-05-01"
      run: |
       docker build . -t vdc:latest
       docker run -v "/vdc/tree/master/Config":"/usr/src/app/Config" -v "/vdc/tree/master/Environments":"/usr/src/app/Environments" -v "/vdc/tree/master/Modules":"/usr/src/app/Modules" vdc:latest
       chmod +x  ./Orchestration/OrchestrationService/ModuleConfigurationDeployment.ps1
       $DebugPreference="Continue"
