name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v2

    - name: Log into Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS  }}  
       
       
    - name: Build the Docker image & Deploy
      id : hello
      uses: jvalley19/vdc@master
      
      run: |
        
        docker run -v "/vdc/tree/master/Config":"/usr/src/app/Config" -v "/vdc/tree/master/Environments":"/usr/src/app/Environments" -v "/vdc/tree/master/Modules":"/usr/src/app/Modules" vdc:latest
        chmod +x  ./Orchestration/OrchestrationService/ModuleConfigurationDeployment.ps1
        ./Orchestration/OrchestrationService/ModuleConfigurationDeployment.ps1 -DefinitionPath ./Environments/SharedServices/definition.json

