name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . -t vdc:latest
      
    - name: Connect Docket toolkit container
      run: docker run -it --rm -v VDC/Config:/usr/src/app/Config -v VDC/Environments:/usr/src/app/Environments -v VDC/Modules:/usr/src/app/Modules vdc:latest
