name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print Env Variables
      env:
        TID: Hi there! My name is
        TNTID: ${{ secrets.TENANT_ID }}
        SID: ${{ secrets.SUBSCRIPTION_ID }}
        KID: ${{ secrets.KEYVAULT_MANAGEMENT_USER_ID }}
      run: |
        echo $TID $SID $KID $TNTID
            
    - name: Build the Docker image
      run: |
       docker build . -t vdc:latest
       docker run -v "/vdc/tree/master/Config":"/usr/src/app/Config" -v "/vdc/tree/master/Environments":"/usr/src/app/Environments" -v "/vdc/tree/master/Modules":"/usr/src/app/Modules" vdc:latest
       chmod +x  ./Orchestration/OrchestrationService/ModuleConfigurationDeployment.ps1
   
       - name: Log into Azure
       - uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
          
    - name: Execute deployment      
      env:
        VDC_SUBSCRIPTIONS: (Get-Content .\Environments\_Common\subscriptions.json -Raw)
        VDC_TOOLKIT_SUBSCRIPTION: (Get-Content .\Config\toolkit.subscription.json -Raw)
        ORGANIZATION_NAME : "MS"
        AZURE_LOCATION : "West US 2"
        AZURE_ENVIRONMENT_NAME : "AzureCloud"
        TENANT_ID : ${{ secrets.TENANT_ID }}
        SUBSCRIPTION_ID : ${{ secrets.SUBSCRIPTION_ID }}
        KEYVAULT_MANAGEMENT_USER_ID  : ${{ secrets.KEYVAULT_MANAGEMENT_USER_ID }}
        AZURE_DISCOVERY_URL : "https://management.azure.com/metadata/endpoints?api-version=2019-05-01"
      run:          
          ./Orchestration/OrchestrationService/ModuleConfigurationDeployment.ps1 -DefinitionPath ./Environments/MS-VDI/definition.json -ModuleConfigurationName "VirtualNetworkHUB"
      shell : pwsh
