name: Tester

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dockflow:
      runs-on: ubuntu-latest
      steps:
        - name: Get the sources 
          uses: actions/checkout@v2
        - name: Hi world action
          uses: ./
          id: hello
        -name: Get output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"
        
        
        name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}  
          


       
      run: |
       docker build . -t vdc:latest
       docker run -v "/vdc/tree/master/Config":"/usr/src/app/Config" -v "/vdc/tree/master/Environments":"/usr/src/app/Environments" -v "/vdc/tree/master/Modules":"/usr/src/app/Modules" vdc:latest
       chmod +x  ./Orchestration/OrchestrationService/ModuleConfigurationDeployment.ps1
       $DebugPreference="Continue"
